### ISSUE TITLE
OrganizationJobFetcher must not use dateModifed to determine when to send update

### ISSUE THREAD

**Issue by TiSiE** [yawik/export-ba#6]
[JobOrganizationFetcher](https://github.com/yawik/export-ba/blob/master/src/JobFetcher/OrganizationJobFetcher.php) uses the modification date of the job entity to determine wether or not the job needs to be updated. This date is always newer than any other date stored in the entity, because it is set via a Doctrine Event Hook.

Unfortunately, there's no way to get the import date from the job entity at the moment.

**Comment by cbleek** [comment]
Sehr gut. Ich habe online eine Änderung vorgenommen, Und zwar:

```
root@stellenmarkt:/var/www/production/current/vendor/yawik/export-ba/views# diff default.phtml default.phtml~                                                                       
35c35                                                                                                                                                                               
<                 <NAICS>70.22.0</NAICS>                                                                                                                                            
---                                                                                                                                                                                 
>                 <NAICS>78.30.0</NAICS>
```

Das ist die Branche für 1A. Das bitte berücksichtigen

**Comment by TiSiE** [comment]
Now implemented using dedicated entities for the export-ba module.
